export const BARBER_LOGGED_IN_MIDDLEWARE_SUCCESS = "BARBER_LOGGED_IN_MIDDLEWARE_SUCCESS"

//AFTER SUCCESSFUL SIGNIN THIS MIDDLEWARE IS CALLING AND IS RESPONSIBLE FOR GIBING CURRENT ADMIN DATA
export const BARBER_GOOGLE_SIGNIN_REQ = "BARBER_GOOGLE_SIGNIN_REQ"
export const BARBER_GOOGLE_SIGNIN_SUCCESS = "BARBER_GOOGLE_SIGNIN_SUCCESS"
export const BARBER_GOOGLE_SIGNIN_FAIL = "BARBER_GOOGLE_SIGNIN_FAIL"

export const BARBER_GOOGLE_SIGNUP_REQ = "BARBER_GOOGLE_SIGNUP_REQ"
export const BARBER_GOOGLE_SIGNUP_SUCCESS = "BARBER_GOOGLE_SIGNUP_SUCCESS"
export const BARBER_GOOGLE_SIGNUP_FAIL = "BARBER_GOOGLE_SIGNUP_FAIL"

export const BARBER_SIGNUP_REQ = "BARBER_SIGNUP_REQ"
export const BARBER_SIGNUP_SUCCESS = "BARBER_SIGNUP_SUCCESS"
export const BARBER_SIGNUP_FAIL = "BARBER_SIGNUP_FAIL"

export const BARBER_SIGNIN_REQ = "BARBER_SIGNIN_REQ"
export const BARBER_SIGNIN_SUCCESS = "BARBER_SIGNIN_SUCCESS"
export const BARBER_SIGNIN_FAIL = "BARBER_SIGNIN_FAIL"

export const BARBER_SIGNUP_EDIT_REQ = "BARBER_SIGNUP_EDIT_REQ"
export const BARBER_SIGNUP_EDIT_SUCCESS = "BARBER_SIGNUP_EDIT_SUCCESS"
export const BARBER_SIGNUP_EDIT_FAIL = "BARBER_SIGNUP_EDIT_FAIL"

export const BARBER_LOGOUT_REQ = "BARBER_LOGOUT_REQ"
export const BARBER_LOGOUT_SUCCESS = "BARBER_LOGOUT_SUCCESS"
export const BARBER_LOGOUT_FAIL = "BARBER_LOGOUT_FAIL"

export const CONNECT_SALON_LIST_REQ = "CONNECT_SALON_LIST_REQ"
export const CONNECT_SALON_LIST_SUCCESS = "CONNECT_SALON_LIST_SUCCESS"
export const CONNECT_SALON_LIST_FAIL = "CONNECT_SALON_LIST_FAIL"

export const BARBER_CONNECT_SALON_REQ = "BARBER_CONNECT_SALON_REQ"
export const BARBER_CONNECT_SALON_SUCCESS = "BARBER_CONNECT_SALON_SUCCESS"
export const BARBER_CONNECT_SALON_FAIL = "BARBER_CONNECT_SALON_FAIL"