export const BARBER_LOGGED_IN_MIDDLEWARE_SUCCESS = "BARBER_LOGGED_IN_MIDDLEWARE_SUCCESS"

//AFTER SUCCESSFUL SIGNIN THIS MIDDLEWARE IS CALLING AND IS RESPONSIBLE FOR GIBING CURRENT ADMIN DATA
export const BARBER_GOOGLE_SIGNIN_REQ = "BARBER_GOOGLE_SIGNIN_REQ"
export const BARBER_GOOGLE_SIGNIN_SUCCESS = "BARBER_GOOGLE_SIGNIN_SUCCESS"
export const BARBER_GOOGLE_SIGNIN_FAIL = "BARBER_GOOGLE_SIGNIN_FAIL"