export const ADMIN_GOOGLE_SIGNIN_REQ = "ADMIN_GOOGLE_SIGNIN_REQ"
export const ADMIN_GOOGLE_SIGNIN_SUCCESS = "ADMIN_GOOGLE_SIGNIN_SUCCESS"
export const ADMIN_GOOGLE_SIGNIN_FAIL = "ADMIN_GOOGLE_SIGNIN_FAIL"

//AFTER SUCCESSFUL SIGNIN THIS MIDDLEWARE IS CALLING AND IS RESPONSIBLE FOR GIVING CURRENT ADMIN DATA
export const ADMIN_LOGGED_IN_MIDDLEWARE_SUCCESS = "ADMIN_LOGGED_IN_MIDDLEWARE_SUCCESS"

export const ADMIN_LOGOUT_REQ = "ADMIN_LOGOUT_REQ"
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL"

export const GET_ALL_ADVERTISEMENT_REQ = "GET_ALL_ADVERTISEMENT_REQ"
export const GET_ALL_ADVERTISEMENT_SUCCESS = "GET_ALL_ADVERTISEMENT_SUCCESS"
export const GET_ALL_ADVERTISEMENT_FAIL = "GET_ALL_ADVERTISEMENT_FAIL"

export const GET_ALL_QUEUELIST_REQ = "GET_ALL_QUEUELIST_REQ"
export const GET_ALL_QUEUELIST_SUCCESS = "GET_ALL_QUEUELIST_SUCCESS"
export const GET_ALL_QUEUELIST_FAIL = "GET_ALL_QUEUELIST_FAIL"

export const GET_DASHBOARD_APPOINTMENT_LIST_REQ = "GET_DASHBOARD_APPOINTMENT_LIST_REQ"
export const GET_DASHBOARD_APPOINTMENT_LIST_SUCCESS = "GET_DASHBOARD_APPOINTMENT_LIST_SUCCESS"
export const GET_DASHBOARD_APPOINTMENT_LIST_FAIL = "GET_DASHBOARD_APPOINTMENT_LIST_FAIL"

export const GET_ADMIN_SALONLIST_REQ = "GET_ADMIN_SALONLIST_REQ"
export const GET_ADMIN_SALONLIST_SUCCESS = "GET_ADMIN_SALONLIST_SUCCESS"
export const GET_ADMIN_SALONLIST_FAIL = "GET_ADMIN_SALONLIST_FAIL"