export const ADMIN_GOOGLE_SIGNIN_REQ = "ADMIN_GOOGLE_SIGNIN_REQ"
export const ADMIN_GOOGLE_SIGNIN_SUCCESS = "ADMIN_GOOGLE_SIGNIN_SUCCESS"
export const ADMIN_GOOGLE_SIGNIN_FAIL = "ADMIN_GOOGLE_SIGNIN_FAIL"

export const ADMIN_GOOGLE_SIGNUP_REQ = "ADMIN_GOOGLE_SIGNUP_REQ"
export const ADMIN_GOOGLE_SIGNUP_SUCCESS = "ADMIN_GOOGLE_SIGNUP_SUCCESS"
export const ADMIN_GOOGLE_SIGNUP_FAIL = "ADMIN_GOOGLE_SIGNUP_FAIL"

export const ADMIN_SIGNUP_REQ = "ADMIN_SIGNUP_REQ"
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_FAIL = "ADMIN_SIGNUP_FAIL"

export const ADMIN_SIGNUP_EDIT_REQ = "ADMIN_SIGNUP_EDIT_REQ"
export const ADMIN_SIGNUP_EDIT_SUCCESS = "ADMIN_SIGNUP_EDIT_SUCCESS"
export const ADMIN_SIGNUP_EDIT_FAIL = "ADMIN_SIGNUP_EDIT_FAIL"

//AFTER SUCCESSFUL SIGNIN THIS MIDDLEWARE IS CALLING AND IS RESPONSIBLE FOR GIVING CURRENT ADMIN DATA
export const ADMIN_LOGGED_IN_MIDDLEWARE_SUCCESS = "ADMIN_LOGGED_IN_MIDDLEWARE_SUCCESS"

export const ADMIN_LOGOUT_REQ = "ADMIN_LOGOUT_REQ"
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL"

export const GET_ALL_ADVERTISEMENT_REQ = "GET_ALL_ADVERTISEMENT_REQ"
export const GET_ALL_ADVERTISEMENT_SUCCESS = "GET_ALL_ADVERTISEMENT_SUCCESS"
export const GET_ALL_ADVERTISEMENT_FAIL = "GET_ALL_ADVERTISEMENT_FAIL"

export const GET_ALL_QUEUELIST_REQ = "GET_ALL_QUEUELIST_REQ"
export const GET_ALL_QUEUELIST_SUCCESS = "GET_ALL_QUEUELIST_SUCCESS"
export const GET_ALL_QUEUELIST_FAIL = "GET_ALL_QUEUELIST_FAIL"

export const GET_DASHBOARD_APPOINTMENT_LIST_REQ = "GET_DASHBOARD_APPOINTMENT_LIST_REQ"
export const GET_DASHBOARD_APPOINTMENT_LIST_SUCCESS = "GET_DASHBOARD_APPOINTMENT_LIST_SUCCESS"
export const GET_DASHBOARD_APPOINTMENT_LIST_FAIL = "GET_DASHBOARD_APPOINTMENT_LIST_FAIL"

export const GET_ADMIN_SALONLIST_REQ = "GET_ADMIN_SALONLIST_REQ"
export const GET_ADMIN_SALONLIST_SUCCESS = "GET_ADMIN_SALONLIST_SUCCESS"
export const GET_ADMIN_SALONLIST_FAIL = "GET_ADMIN_SALONLIST_FAIL"

export const GET_ADMIN_BARBERLIST_REQ = "GET_ADMIN_BARBERLIST_REQ"
export const GET_ADMIN_BARBERLIST_SUCCESS = "GET_ADMIN_BARBERLIST_SUCCESS"
export const GET_ADMIN_BARBERLIST_FAIL = "GET_ADMIN_BARBERLIST_FAIL"

export const CHANGE_ADMIN_BARBER_ONLINESTATUS_REQ = "CHANGE_ADMIN_BARBER_ONLINESTATUS_REQ"
export const CHANGE_ADMIN_BARBER_ONLINESTATUS_SUCCESS = "CHANGE_ADMIN_BARBER_ONLINESTATUS_SUCCESS"
export const CHANGE_ADMIN_BARBER_ONLINESTATUS_FAIL = "CHANGE_ADMIN_BARBER_ONLINESTATUS_FAIL"

export const ADMIN_APPROVE_BARBER_REQ = "ADMIN_APPROVE_BARBER_REQ"
export const ADMIN_APPROVE_BARBER_SUCCESS = "ADMIN_APPROVE_BARBER_SUCCESS"
export const ADMIN_APPROVE_BARBER_FAIL = "ADMIN_APPROVE_BARBER_FAIL"

export const ADMIN_ALL_SALON_SERVICES_REQ = "ADMIN_ALL_SALON_SERVICES_REQ"
export const ADMIN_ALL_SALON_SERVICES_SUCCESS = "ADMIN_ALL_SALON_SERVICES_SUCCESS"
export const ADMIN_ALL_SALON_SERVICES_FAIL = "ADMIN_ALL_SALON_SERVICES_FAIL"

export const ADMIN_CREATE_BARBER_REQ = "ADMIN_CREATE_BARBER_REQ"
export const ADMIN_CREATE_BARBER_SUCCESS = "ADMIN_CREATE_BARBER_SUCCESS"
export const ADMIN_CREATE_BARBER_FAIL = "ADMIN_CREATE_BARBER_FAIL"

export const ADMIN_UPDATE_BARBER_REQ = "ADMIN_UPDATE_BARBER_REQ"
export const ADMIN_UPDATE_BARBER_SUCCESS = "ADMIN_UPDATE_BARBER_SUCCESS"
export const ADMIN_UPDATE_BARBER_FAIL = "ADMIN_UPDATE_BARBER_FAIL"

export const ADMIN_DELETE_BARBER_REQ = "ADMIN_DELETE_BARBER_REQ"
export const ADMIN_DELETE_BARBER_SUCCESS = "ADMIN_DELETE_BARBER_SUCCESS"
export const ADMIN_DELETE_BARBER_FAIL = "ADMIN_DELETE_BARBER_FAIL"

export const ADMIN_GETALLSALON_ICONS_REQ = "ADMIN_GETALLSALON_ICONS_REQ"
export const ADMIN_GETALLSALON_ICONS_SUCCESS = "ADMIN_GETALLSALON_ICONS_SUCCESS"
export const ADMIN_GETALLSALON_ICONS_FAIL = "ADMIN_GETALLSALON_ICONS_FAIL"

export const ADMIN_GET_ALL_COUNTRIES_REQ = "ADMIN_GET_ALL_COUNTRIES_REQ"
export const ADMIN_GET_ALL_COUNTRIES_SUCCESS = "ADMIN_GET_ALL_COUNTRIES_SUCCESS"
export const ADMIN_GET_ALL_COUNTRIES_FAIL = "ADMIN_GET_ALL_COUNTRIES_FAIL"

export const ADMIN_GET_ALL_CITIES_REQ = "ADMIN_GET_ALL_CITIES_REQ"
export const ADMIN_GET_ALL_CITIES_SUCCESS = "ADMIN_GET_ALL_CITIES_SUCCESS"
export const ADMIN_GET_ALL_CITIES_FAIL = "ADMIN_GET_ALL_CITIES_FAIL"

export const ADMIN_GET_ALL_TIMEZONES_REQ = "ADMIN_GET_ALL_TIMEZONES_REQ"
export const ADMIN_GET_ALL_TIMEZONES_SUCCESS = "ADMIN_GET_ALL_TIMEZONES_SUCCESS"
export const ADMIN_GET_ALL_TIMEZONES_FAIL = "ADMIN_GET_ALL_TIMEZONES_FAIL"

export const ADMIN_DELETE_SALON_REQ = "ADMIN_DELETE_SALON_REQ"
export const ADMIN_DELETE_SALON_SUCCESS = "ADMIN_DELETE_SALON_SUCCESS"
export const ADMIN_DELETE_SALON_FAIL = "ADMIN_DELETE_SALON_FAIL"

export const ADMIN_CREATE_SALON_REQ = "ADMIN_CREATE_SALON_REQ"
export const ADMIN_CREATE_SALON_SUCCESS = "ADMIN_CREATE_SALON_SUCCESS"
export const ADMIN_CREATE_SALON_FAIL = "ADMIN_CREATE_SALON_FAIL"

export const ADMIN_EDIT_SALON_REQ = "ADMIN_EDIT_SALON_REQ"
export const ADMIN_EDIT_SALON_SUCCESS = "ADMIN_EDIT_SALON_SUCCESS"
export const ADMIN_EDIT_SALON_FAIL = "ADMIN_EDIT_SALON_FAIL"

export const ADMIN_UPDATE_PROFILE_REQ = "ADMIN_UPDATE_PROFILE_REQ"
export const ADMIN_UPDATE_PROFILE_SUCCESS = "ADMIN_UPDATE_PROFILE_SUCCESS"
export const ADMIN_UPDATE_PROFILE_FAIL = "ADMIN_UPDATE_PROFILE_FAIL"

export const GET_ALL_CUSTOMERLIST_REQ = "GET_ALL_CUSTOMERLIST_REQ"
export const GET_ALL_CUSTOMERLIST_SUCCESS = "GET_ALL_CUSTOMERLIST_SUCCESS"
export const GET_ALL_CUSTOMERLIST_FAIL = "GET_ALL_CUSTOMERLIST_FAIL"

export const ADMIN_BARBER_SERVED_QUEUE_REQ = "ADMIN_BARBER_SERVED_QUEUE_REQ"
export const ADMIN_BARBER_SERVED_QUEUE_SUCCESS = "ADMIN_BARBER_SERVED_QUEUE_SUCCESS"
export const ADMIN_BARBER_SERVED_QUEUE_FAIL  = "ADMIN_BARBER_SERVED_QUEUE_FAIL"

export const ADMIN_CANCEL_QUEUE_REQ = "ADMIN_CANCEL_QUEUE_REQ"
export const ADMIN_CANCEL_QUEUE_SUCCESS = "ADMIN_CANCEL_QUEUE_SUCCESS"
export const ADMIN_CANCEL_QUEUE_FAIL  = "ADMIN_CANCEL_QUEUE_FAIL"

export const ADMIN_SEND_VERIFY_EMAIL_REQ = "ADMIN_SEND_VERIFY_EMAIL_REQ"
export const ADMIN_SEND_VERIFY_EMAIL_SUCCESS = "ADMIN_SEND_VERIFY_EMAIL_SUCCESS"
export const ADMIN_SEND_VERIFY_EMAIL_FAIL = "ADMIN_SEND_VERIFY_EMAIL_FAIL"

export const ADMIN_VERIFIED_EMAIL_STATUS_REQ = "ADMIN_VERIFIED_EMAIL_STATUS_REQ"
export const ADMIN_VERIFIED_EMAIL_STATUS_SUCCESS = "ADMIN_VERIFIED_EMAIL_STATUS_SUCCESS"
export const ADMIN_VERIFIED_EMAIL_STATUS_FAIL = "ADMIN_VERIFIED_EMAIL_STATUS_FAIL"

export const ADMIN_APPLY_SALON_REQ = "ADMIN_APPLY_SALON_REQ"
export const ADMIN_APPLY_SALON_SUCCESS = "ADMIN_APPLY_SALON_SUCCESS"
export const ADMIN_APPLY_SALON_FAIL = "ADMIN_APPLY_SALON_FAIL"

export const ADMIN_GET_DEFAULT_SALON_REQ = "ADMIN_GET_DEFAULT_SALON_REQ"
export const ADMIN_GET_DEFAULT_SALON_SUCCESS = "ADMIN_GET_DEFAULT_SALON_SUCCESS"
export const ADMIN_GET_DEFAULT_SALON_FAIL = "ADMIN_GET_DEFAULT_SALON_FAIL"

export const SALON_ONLINE_STATUS_REQ = "SALON_ONLINE_STATUS_REQ"
export const SALON_ONLINE_STATUS_SUCCESS = "SALON_ONLINE_STATUS_SUCCESS"
export const SALON_ONLINE_STATUS_FAIL = "SALON_ONLINE_STATUS_FAIL"